name: Publish release APK

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  package-release-apk:
    name: Generate release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for app release
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Decode Keystore
        id: decode_keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.jks

      - name: Build with Gradle
        run: ./gradlew :composeApp:assembleRelease --stacktrace
        env:
            STORE_FILE: release.jks
            STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
            KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
            KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    
      # Upload your signed file if you want
      - uses: actions/upload-artifact@v4
        with:
          name: Signed app bundle
          path: composeApp/build/outputs/apk/release
