name: Publish release APK

on:
  push:
    branches:
      - master # Triggers on push or merge to master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  package-release-apk:
    name: Generate release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for app release
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Decode Keystore
        id: decode_keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.jks

      - name: Build with Gradle
        id: build_app
        run: ./gradlew :composeApp:assembleRelease --stacktrace
        env:
            STORE_FILE: release.jks
            STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
            KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
            KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - uses: NoCrypt/sign-android@main
        id: sign_app
        with:
          releaseDir: composeApp/build/outputs/apk/release
          signingKey: ${{ secrets.KEYSTORE_BASE64 }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Parse JSON file get version
        id: version
        run: |
          VALUE=$(jq -r '.elements.[0].versionName' composeApp/build/outputs/apk/release/output-metadata.json)
          echo "app_version=$VALUE" >> $GITHUB_OUTPUT

      - name: Parse JSON file get app name
        id: file
        run: |
          VALUE=$(jq -r '.elements.[0].outputFile' composeApp/build/outputs/apk/release/output-metadata.json)
          echo "output_file=$VALUE" >> $GITHUB_OUTPUT

      - name: Create JSON
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "changelog.json"
          json: '{"latest_version": "${{ steps.version.outputs.app_version }}", "changelog": "Исправлены ошибки и улучшена производительность", "apk_url": "https://github.com/khokhlovn/CorpPortalMobile/releases/download/latest/${{ steps.file.outputs.output_file }}"}'
          dir: "composeApp/build/outputs/apk/release/"
    
      # Upload your signed file if you want
      - uses: actions/upload-artifact@v4
        with:
          name: Signed app bundle
          path: composeApp/build/outputs/apk/release

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Development Build"
          files: |
            composeApp/build/outputs/apk/release/*.apk
            composeApp/build/outputs/apk/release/changelog.json
