name: Publish release APK

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  package-release-apk:
    name: Generate release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for app release
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: 21

      - uses: ilharp/sign-android-release@v2 # Or use @nightly
        name: Sign app APK
        id: sign_app
        with:
          releaseDir: composeApp/release
          signingKey: ${{ secrets.KEYSTORE_BASE64 }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: 36.0.0
    
      # Upload your signed file if you want
      - uses: actions/upload-artifact@v4
        with:
          name: Signed app bundle
          path: ${{steps.sign_app.outputs.signedFile}}
